#version 430 core
layout(local_size_x = 64) in;

layout(std430, binding = 0) buffer Input { float numbers[]; } inBuf;
layout(std430, binding = 1) buffer Output { float squaredNums[]; } outBuf;

uniform int count; // max amount of nums

void main() {
    uint i = gl_GlobalInvocationID.x; // unique per element
    if (i >= count) return;

    outBuf.squaredNums[i] = inBuf.numbers[i] * inBuf.numbers[i];
}